=== darrellcolehill/Codex-Scripture-Editor-GWT-Extension/media/ulb_tagged_checked/wa_ulb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="xml" type="xmlType"/>
  <xs:complexType name="usfmType">
    <xs:simpleContent>
      <xs:extension base="xs:string" />
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="wType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:integer" name="OGNTsort" use="optional"/>
        <xs:attribute name="strongs" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:whiteSpace value="collapse"/>
                    <xs:pattern value="G([0-9])*" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute type="xs:string" name="morph" use="optional"/>
        <xs:attribute type="xs:string" name="lemma" use="optional"/>
        <xs:attribute type="xs:string" name="text" use="optional"/>
        <xs:attribute type="xs:string" name="sub" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="phraseWordsType" mixed="true">
    <xs:all>
      <xs:element name="usfm" type="usfmType"  minOccurs="0" />
    </xs:all>
  </xs:complexType>
  <xs:complexType name="phraseType" mixed="true">
    <xs:sequence>
      <xs:element type="wType" name="w" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element name="phraseWords" minOccurs="1" type="phraseWordsType" />
    </xs:sequence>
    <xs:attribute type="xs:string" name="sub" use="optional"/>
  </xs:complexType>
  <xs:group name="verseHeaderGroup">
    <xs:sequence>
      <xs:element type="xs:string" name="Greek"/>
      <xs:element type="xs:string" name="preText"/>
      <xs:element name="ULB">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="usfmType" name="usfm" maxOccurs="unbounded" minOccurs="0" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element type="xs:string" name="residue"/>
    </xs:sequence>
  </xs:group>
  <xs:group name="wordsGroup">
    <xs:choice>
      <xs:element type="wType" name="w"/>
      <xs:element type="phraseType" name="phrase"/>
      <xs:element type="usfmType" name="usfm"/>
      <xs:element type="xs:string" name="comment"/>
    </xs:choice>
  </xs:group>
  <xs:complexType name="verseType">
    <xs:sequence>
      <xs:group ref="verseHeaderGroup" minOccurs="1"/>
      <xs:group ref="wordsGroup" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="chapterType">
    <xs:sequence>
      <xs:element type="verseType" name="verse" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="osisID" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ULBType" mixed="true">
    <xs:sequence>
      <xs:element name="usfm" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string" />
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="bookType">
    <xs:sequence>
      <xs:element type="chapterType" name="chapter" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="osisID"/>
  </xs:complexType>
  <xs:complexType name="xmlType">
    <xs:sequence>
      <xs:element type="bookType" name="book"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== darrellcolehill/Codex-Scripture-Editor-GWT-Extension/media/ulb_tagged_checked/64-2JN.xml
<?xml version="1.0" standalone="yes" ?>
<xml xsi:schemaLocation="wa_ulb.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<book osisID="2jn">
		<chapter osisID="2jn.1">
			<verse name="2 John 1:1">
				<Greek>Ὁ πρεσβύτερος Ἐκλεκτῇ κυρίᾳ καὶ τοῖς τέκνοις αὐτῆς οὓς ἐγὼ ἀγαπῶ ἐν ἀληθείᾳ καὶ οὐκ ἐγὼ μόνος ἀλλὰ καὶ πάντες οἱ ἐγνωκότες τὴν ἀλήθειαν</Greek>
				<preText>\s5 \c 1 \p \v 1</preText>
				<ULB>From the elder to the chosen lady and her children, whom I love in truth—and not only I, but also all those who have known the truth—</ULB>
				<residue>From the  to the  lady and her  , whom I  in  —and not only I, but also all those who have  the  —</residue>
				<w>From</w>
				<w OGNTsort="127242" strongs="G3588" morph="T-NSM" lemma="ὁ" text="Ὁ">the</w>
				<w OGNTsort="127243" strongs="G4245" morph="A-NSM" lemma="πρεσβύτερος" text="πρεσβύτερος">elder</w>
				<w OGNTsort="127244" strongs="G1588" morph="A-DSF" lemma="ἐκλεκτός" text="Ἐκλεκτῇ">to the chosen</w>
				<w OGNTsort="127245" strongs="G2959" morph="N-DSF" lemma="Κυρία" text="κυρίᾳ">lady</w>
				<w OGNTsort="127246" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">and</w>
				<w OGNTsort="127249" strongs="G846" morph="P-GSF" lemma="αὐτός" text="αὐτῆς">her</w>
				<w OGNTsort="127247" strongs="G3588" morph="T-DPN" lemma="ὁ" text="τοῖς">√</w>
				<w OGNTsort="127248" strongs="G5043" morph="N-DPN" lemma="τέκνον" text="τέκνοις">children,</w>
				<w OGNTsort="127250" strongs="G3739" morph="R-APM" lemma="ὅς, ἥ" text="οὓς">whom</w>
				<w OGNTsort="127251" strongs="G1473" morph="P-1NS" lemma="ἐγώ" text="ἐγὼ">I</w>
				<w OGNTsort="127252" strongs="G25" morph="V-PAI-1S" lemma="ἀγαπάω" text="ἀγαπῶ">love</w>
				<w OGNTsort="127253" strongs="G1722" morph="PREP" lemma="ἐν" text="ἐν">in</w>
				<w OGNTsort="127254" strongs="G225" morph="N-DSF" lemma="ἀλήθεια" text="ἀληθείᾳ">truth—</w>
				<w OGNTsort="127255" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">and</w>
				<w OGNTsort="127256" strongs="G3756" morph="PRT-N" lemma="οὐ" text="οὐκ">not</w>
				<w OGNTsort="127258" strongs="G3441" morph="A-NSM" lemma="μόνος" text="μόνος">only</w>
				<w OGNTsort="127257" strongs="G1473" morph="P-1NS" lemma="ἐγώ" text="ἐγὼ">I,</w>
				<w OGNTsort="127259" strongs="G235" morph="CONJ" lemma="ἀλλά" text="ἀλλὰ">but</w>
				<w OGNTsort="127260" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">also</w>
				<w OGNTsort="127261" strongs="G3956" morph="A-NPM" lemma="πᾶς" text="πάντες">all</w>
				<w OGNTsort="127262" strongs="G3588" morph="T-NPM" lemma="ὁ" text="οἱ">those who</w>
				<w OGNTsort="127263" strongs="G1097" morph="V-RAP-NPM" lemma="γινώσκω" text="ἐγνωκότες">have known</w>
				<w OGNTsort="127264" strongs="G3588" morph="T-ASF" lemma="ὁ" text="τὴν">the</w>
				<w OGNTsort="127265" strongs="G225" morph="N-ASF" lemma="ἀλήθεια" text="ἀλήθειαν">truth—</w>
			</verse>
			<verse name="2 John 1:2">
				<Greek>διὰ τὴν ἀλήθειαν τὴν μένουσαν ἐν ἡμῖν καὶ μεθ᾽ ἡμῶν ἔσται εἰς τὸν αἰῶνα</Greek>
				<preText>\v 2</preText>
				<ULB>because of the truth that remains in us and will be with us forever.</ULB>
				<residue>because of the  that remains in us and will be with us  .</residue>
				<w OGNTsort="127266" strongs="G1223" morph="PREP" lemma="διά" text="διὰ">because of</w>
				<w OGNTsort="127267" strongs="G3588" morph="T-ASF" lemma="ὁ" text="τὴν">the</w>
				<w OGNTsort="127268" strongs="G225" morph="N-ASF" lemma="ἀλήθεια" text="ἀλήθειαν">truth</w>
				<w OGNTsort="127269" strongs="G3588" morph="T-ASF" lemma="ὁ" text="τὴν">that</w>
				<w OGNTsort="127270" strongs="G3306" morph="V-PAP-ASF" lemma="μένω" text="μένουσαν">remains</w>
				<w OGNTsort="127271" strongs="G1722" morph="PREP" lemma="ἐν" text="ἐν">in</w>
				<w OGNTsort="127272" strongs="G1473" morph="P-1DP" lemma="ἐγώ" text="ἡμῖν">us</w>
				<w OGNTsort="127273" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">and</w>
				<w OGNTsort="127276" strongs="G1510" morph="V-FDI-3S" lemma="εἰμί" text="ἔσται">will be</w>
				<w OGNTsort="127274" strongs="G3326" morph="PREP" lemma="μετά" text="μεθ᾽">with</w>
				<w OGNTsort="127275" strongs="G1473" morph="P-1GP" lemma="ἐγώ" text="ἡμῶν">us</w>
				<phrase>
					<w OGNTsort="127277" strongs="G1519" morph="PREP" lemma="εἰς" text="εἰς">√</w>
					<w OGNTsort="127278" strongs="G3588" morph="T-ASM" lemma="ὁ" text="τὸν">√</w>
					<w OGNTsort="127279" strongs="G165" morph="N-ASM" lemma="αἰών" text="αἰῶνα">√</w>
					<phraseWords>forever.</phraseWords>
				</phrase>
			</verse>
			<verse name="2 John 1:3">
				<Greek>Ἔσται μεθ᾽ ἡμῶν χάρις ἔλεος εἰρήνη παρὰ Θεοῦ Πατρός καὶ παρὰ Ἰησοῦ Χριστοῦ τοῦ Υἱοῦ τοῦ Πατρός ἐν ἀληθείᾳ καὶ ἀγάπῃ</Greek>
				<preText>\p \v 3</preText>
				<ULB>Grace, mercy, and peace will be with us from God the Father and from Jesus Christ, the Son of the Father, in truth and love.</ULB>
				<residue>Grace,  , and  will be with us from  and from  ,  of the  , in  and  .</residue>
				<w OGNTsort="127283" strongs="G5485" morph="N-NSF" lemma="χάρις" text="χάρις">Grace,</w>
				<w OGNTsort="127284" strongs="G1656" morph="N-NSN" lemma="ἔλεος" text="ἔλεος">mercy,</w>
				<w>and</w>
				<w OGNTsort="127285" strongs="G1515" morph="N-NSF" lemma="εἰρήνη" text="εἰρήνη">peace</w>
				<w OGNTsort="127280" strongs="G1510" morph="V-FDI-3S" lemma="εἰμί" text="Ἔσται">will be</w>
				<w OGNTsort="127281" strongs="G3326" morph="PREP" lemma="μετά" text="μεθ᾽">with</w>
				<w OGNTsort="127282" strongs="G1473" morph="P-1GP" lemma="ἐγώ" text="ἡμῶν">us</w>
				<w OGNTsort="127286" strongs="G3844" morph="PREP" lemma="παρά" text="παρὰ">from</w>
				<w OGNTsort="127287" strongs="G2316" morph="N-GSM" lemma="θεός" text="Θεοῦ">God</w>
				<w OGNTsort="127288" strongs="G3962" morph="N-GSM" lemma="πατήρ" text="Πατρός">the Father</w>
				<w OGNTsort="127289" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">and</w>
				<w OGNTsort="127290" strongs="G3844" morph="PREP" lemma="παρά" text="παρὰ">from</w>
				<w OGNTsort="127291" strongs="G2424" morph="N-GSM-P" lemma="Ἰησοῦς" text="Ἰησοῦ">Jesus</w>
				<w OGNTsort="127292" strongs="G5547" morph="N-GSM-T" lemma="Χριστός" text="Χριστοῦ">Christ,</w>
				<w OGNTsort="127293" strongs="G3588" morph="T-GSM" lemma="ὁ" text="τοῦ">the</w>
				<w OGNTsort="127294" strongs="G5207" morph="N-GSM" lemma="υἱός" text="Υἱοῦ">Son</w>
				<w OGNTsort="127295" strongs="G3588" morph="T-GSM" lemma="ὁ" text="τοῦ">of the</w>
				<w OGNTsort="127296" strongs="G3962" morph="N-GSM" lemma="πατήρ" text="Πατρός">Father,</w>
				<w OGNTsort="127297" strongs="G1722" morph="PREP" lemma="ἐν" text="ἐν">in</w>
				<w OGNTsort="127298" strongs="G225" morph="N-DSF" lemma="ἀλήθεια" text="ἀληθείᾳ">truth</w>
				<w OGNTsort="127299" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">and</w>
				<w OGNTsort="127300" strongs="G26" morph="N-DSF" lemma="ἀγάπη" text="ἀγάπῃ">love.</w>
			</verse>
			<verse name="2 John 1:4">
				<Greek>Ἐχάρην λίαν ὅτι εὕρηκα ἐκ τῶν τέκνων σου περιπατοῦντας ἐν ἀληθείᾳ καθὼς ἐντολὴν ἐλάβομεν παρὰ τοῦ Πατρός</Greek>
				<preText>\s5 \p \v 4</preText>
				<ULB>I rejoice greatly that I have found some of your children walking in truth, just as we have received this commandment from the Father.</ULB>
				<residue>I  greatly that I have found some of your  in  ,  we have  this  from the  .</residue>
				<w OGNTsort="127301" strongs="G5463" morph="V-2AOI-1S" lemma="χαίρω" text="Ἐχάρην">I rejoice</w>
				<w OGNTsort="127302" strongs="G3029" morph="ADV" lemma="λίαν" text="λίαν">greatly</w>
				<w OGNTsort="127303" strongs="G3754" morph="CONJ" lemma="ὅτι" text="ὅτι">that</w>
				<w OGNTsort="127304" strongs="G2147" morph="V-RAI-1S" lemma="εὑρίσκω" text="εὕρηκα">I have found</w>
				<w>some</w>
				<w OGNTsort="127305" strongs="G1537" morph="PREP" lemma="ἐκ" text="ἐκ">of</w>
				<w OGNTsort="127308" strongs="G4771" morph="P-2GS" lemma="σύ" text="σου">your</w>
				<w OGNTsort="127306" strongs="G3588" morph="T-GPN" lemma="ὁ" text="τῶν">√</w>
				<w OGNTsort="127307" strongs="G5043" morph="N-GPN" lemma="τέκνον" text="τέκνων">children</w>
				<w OGNTsort="127309" strongs="G4043" morph="V-PAP-APM" lemma="περιπατέω" text="περιπατοῦντας">walking</w>
				<w OGNTsort="127310" strongs="G1722" morph="PREP" lemma="ἐν" text="ἐν">in</w>
				<w OGNTsort="127311" strongs="G225" morph="N-DSF" lemma="ἀλήθεια" text="ἀληθείᾳ">truth,</w>
				<w OGNTsort="127312" strongs="G2531" morph="CONJ" lemma="καθώς" text="καθὼς">just as</w>
				<w OGNTsort="127314" strongs="G2983" morph="V-2AAI-1P" lemma="λαμβάνω" text="ἐλάβομεν">we have received</w>
				<w>this</w>
				<w OGNTsort="127313" strongs="G1785" morph="N-ASF" lemma="ἐντολή" text="ἐντολὴν">commandment</w>
				<w OGNTsort="127315" strongs="G3844" morph="PREP" lemma="παρά" text="παρὰ">from</w>
				<w OGNTsort="127316" strongs="G3588" morph="T-GSM" lemma="ὁ" text="τοῦ">the</w>
				<w OGNTsort="127317" strongs="G3962" morph="N-GSM" lemma="πατήρ" text="Πατρός">Father.</w>
			</verse>
			<verse name="2 John 1:5">
				<Greek>καὶ νῦν ἐρωτῶ σε κυρία οὐχ ὡς ἐντολὴν γράφων σοι καινὴν ἀλλὰ ἣν εἴχομεν ἀπ᾽ ἀρχῆς ἵνα ἀγαπῶμεν ἀλλήλους</Greek>
				<preText>\v 5</preText>
				<ULB>Now I plead with you, lady—not as though I were writing to you a new commandment, but one that we have had from the beginning—that we should love one another.</ULB>
				<residue>Now I  with you, lady—not as though I were writing to you a new  , but one that we have had from the beginning—that we should  one another.</residue>
				<w OGNTsort="127318" strongs="G2532" morph="CONJ" lemma="καί" text="καὶ">√</w>
				<w OGNTsort="127319" strongs="G3568" morph="ADV" lemma="νῦν" text="νῦν">Now</w>
				<w OGNTsort="127320" strongs="G2065" morph="V-PAI-1S" lemma="ἐρωτάω" text="ἐρωτῶ">I plead with</w>
				<w OGNTsort="127321" strongs="G4771" morph="P-2AS" lemma="σύ" text="σε">you,</w>
				<w OGNTsort="127322" strongs="G2959" morph="N-VSF" lemma="Κυρία" text="κυρία">lady—</w>
				<w OGNTsort="127323" strongs="G3756" morph="PRT-N" lemma="οὐ" text="οὐχ">not</w>
				<phrase>
